### ISSUE TITLE
 null is not an object (evaluating '_reactNativePgReactNativeSdk.default.startPaymentWEB')

### ISSUE THREAD

**Issue by shivani2911** [cashfree/react-native-pgsdk-demo-app#1]
When i call the url with all param 
 var map = {
            "appId": STRINGNAME.AppId,
            "orderId": orderId,
            "orderAmount": orderAmount,
            "orderNote": "Cashfree Test",
            "customerName": "Cashfree",
            "customerPhone": "9481758674",
            "customerEmail": "arjun@cashfree.com",
            "notifyUrl": "",
            "orderCurrency": orderCurrency,
            "tokenData": token
        }

        RNPgReactNativeSDK.startPaymentWEB(map, 'Test', (someData) => {
            console.log("FROM React_Native", someData);
        });

it returns me the below error 
 Possible Unhandled Promise Rejection (id: 2):
                             │ TypeError: null is not an object (evaluating '_reactNativePgReactNativeSdk.default.startPaymentWEB')
                             │ payUrlCall$
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24976:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25149:32
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24976:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25049:30
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25079:19
                             │ tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27065:9
                             │ doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27229:25
                             │ Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27088:14
                             │ callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25078:33
                             │ enqueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25083:157
                             │ async@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25100:69
                             │ getToken$
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24976:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25149:32
                             │ tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:24976:23
                             │ invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25049:30
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25059:21
                             │ tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27056:16
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27157:27
                             │ _callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30596:17
                             │ _callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30635:17
                             │ callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30852:33
                             │ __callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2736:35
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2522:34
                             │ __guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2719:15
                             │ flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2521:21
                             │ flushedQueue@[native code]
                             └ callFunctionReturnFlushedQueue@[native code]

Help to solve this error

**Comment by cjoshi85** [comment]
@shivani2911 was this error resolved?

**Comment by shivani2911** [comment]
noo

**Comment by aabhasr1** [comment]
@shivani2911 was the result resolved?
