### ISSUE TITLE
Invalid order data

### ISSUE THREAD

**Issue by masnoonmulla** [cashfree/react-native-pgsdk-demo-app#6]
![WhatsApp Image 2022-04-13 at 5 59 31 PM](https://user-images.githubusercontent.com/36194265/163180658-53e3c36b-a7c7-4771-b7be-ed174037170a.jpeg)

HI, iam getting this in startPaymentWEB(),
Please help me out. Thank you

**Comment by prem-cashfree** [comment]
Can you please send the request data to techsupport@cashfree.com.

**Comment by masnoonmulla** [comment]
Hi @prem-cashfree I have mail  the request data on same,kindly look in to it.

> Can you please send the request data to [techsupport@cashfree.com](mailto:techsupport@cashfree.com).

**Comment by prem-cashfree** [comment]
> 

@masnoonmulla So order-id(Order0***) which you are sending in order token and order-id(bex_order_********) which you are sending in payload are not same that's why it's showing invalid order id.

**Comment by masnoonmulla** [comment]
@prem-cashfree Thanks for the reply. it now with same order id.
