### ISSUE TITLE
Cashfree SDK not opening on IOS 

### ISSUE THREAD

**Issue by bextechnologies** [cashfree/react-native-pgsdk-demo-app#8]
Hello,
We run in to small issue, your payment SDK is functioning on Android, but on IOS it's not opening SDK and there is no error messages.

We followed this **Step 2c: Set up the SDK (iOS)** and still not result

"react-native": "^0.64.2".
"react-native-pg-react-native-sdk": "^2.1.7",
"XCODE":Version 13.2.1 (13C100)

**Comment by suhas-cashfree** [comment]
Hi Team,

**Comment by bextechnologies** [comment]
@suhas-cashfree Thanks for reply,
There is no logs are printing

**Comment by suhas-cashfree** [comment]
Please run the application from XCode and share the logs generated by XCode

**Comment by bextechnologies** [comment]
2022-04-19 11:30:52.546647+0530 Bex[19234:208679] CF::SDK::IOS::WEB::INVOKED
2022-04-19 11:30:52.798425+0530 Bex[19234:213222] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
script 
<html><body onload='document.order.submit()'><form name='order' action='https://test.cashfree.com/billpay/checkout/post/submit' method='post'><input type='hidden' name='appId' value='151270c422003c31f64b635afa072151'><input type='hidden' name='orderId' value='bex_order_INSX2okrvj5lJZczCJaFt'/><input type='hidden' name='customerEmail' value='shareyas@gmail.com'/><input type='hidden' name='appId' value='151270c422003c31f64b635afa072151'/><input type='hidden' name='orderCurrency' value='INR'/><input type='hidden' name='color1' value='#AAA6D6'/><input type='hidden' name='customerPhone' value='1234567980'/><input type='hidden' name='source' value='react-native-ios-sdk'/><input type='hidden' name='customerName' value='Tean'/><input type='hidden' name='orderAmount' value='135'/><input type='hidden' name='tokenData' value='QH9JCN4MzUIJiOicGbhJCLiQ1VKJiOiAXe0Jye.UY9JSMxEzY5QTMwUTZ1IjNiojI0xWYz9lIsITNwADN5ITN2EjOiAHelJCLiIlTJJiOik3YuVmcyV3QyVGZy9mIsUzMxojI05Wdv1WQyVGZy9mIsICdGFmSDp3YapEb1omdyt2byg1UOl0XyVGZy92X4VmYiojIklkclRmcvJye.WHYvCLr_slFuUWE9rd2dFaGj6dN73ic3sq4BYxIFAhPnliCnozKDe0nCRNx40qtoKs'/><input type='hidden' name='source' value='react-native-ios-sdk'/><input type='hidden' name='hideHeader' value='1'/></form></body></html>
2022-04-19 11:30:53.861228+0530 Bex[19234:208679] [Presentation] Attempt to present <CFSDK.CFViewController: 0x7fecf9290000> on <UIViewController: 0x7fecf8f23430> (from <UIViewController: 0x7fecf8f23430>) which is already presenting <RCTModalHostViewController: 0x7fed022f4240>.

**Comment by suhas-cashfree** [comment]
Hi Team,
If the screen invoking the SDK is presented using a <Modal>, please change it to something different or close it before invoking the SDK.

The screen is trying to present Cashfree's web page on top of your Modal screen and it's not able to.

**Comment by bextechnologies** [comment]
@suhas-cashfree Thanks for your support. it works
